# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2fc18a3e55931e693947147592ebef8caea235a56a8bb9c9d2f51de600a532e38ba1557dfbf1ec042d6de538ee629c90aa6f9560e094154be3ab23b51dfc0ed

test:
  secret_key_base: 257b2d31babb41b8322b92e10f97574747c35644a03c69274e8c59a20a73c029f4bc83089b76e5b1e262d34c632c25cb37f83cb69f2c557ebb8fdfe96a03c948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
